server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: postgres
    source: ${DATABASE_SOURCE:host=127.0.0.1 port=5432 user=postgres password=postgres dbname=project_hq sslmode=disable}
    debug: true
    auto_migrate: true

  redis:
    addr: ${REDIS_ADDR:127.0.0.1:6379}
    read_timeout: 0.2s
    write_timeout: 0.2s